[tool.poetry]
name = "parser_generator"
version = "0.0.1"
description = "Generates a parser from the given grammar."
authors = ["Terrence Reilly <terrencepreilly@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
bnf_to_cnf = { path = "../bnf_to_cnf" }
darglint = "^1.5.8"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
mypy = "^0.931"
autopep8 = "^1.5.0"
python-language-server = {extras = ["all"], version = "^0.36.2"}
pyls-mypy = "^0.1.8"
black = "^22.1"

[tool.black]
exclude = '(.env|.mypy_cache)'
line_length = 80

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
genparse = "parser_generator.driver:main"
